name: Test SSH Connection
on:
  push:
    branches:
      - main

env:
  CONTEXT_PATH: .
  DOCKER_PATH: ./Dockerfile
  IMAGE_NAME: todo
  ENVIRONMENT: dev
      
jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: copy env
      #   run: |
      #     cp /path/to/.env ./

      - name: Build docker image
        run: |
          docker build -t ${{env.IMAGE_NAME}}:${{env.ENVIRONMENT}} .
        
      - name: Save the docker image as tar file
        run: |
          mkdir -p ~/imagetar
          docker save ${{env.IMAGE_NAME}}:${{env.ENVIRONMENT}} > ~/imagetar/${{env.IMAGE_NAME}}:${{env.ENVIRONMENT}}.tar
          ls ~/imagetar

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_ed25519
          sudo chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} whoami

      - name: Set docker context 
        run: |
          docker context create ec2 --docker "host=ssh://${{ secrets.USERNAME }}@${{ secrets.HOST }}"

      - name: Verify Docker Context
        run: |
          docker context ls

      # - name: Load the docker image into remote context
      #   run: | 
      #     docker context use ec2

      #     docker load -i ~/imagetar/${{env.IMAGE_NAME}}:${{env.ENVIRONMENT}}.tar
