name: Build docker image
on: 
  push:
    branches:
      - main

env: 
  CONTEXT_PATH: .
  DOCKER_PATH: ./Dockerfile
  IMAGE_NAME: todo
  ENVIRONMENT: dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build -t ${{env.IMAGE_NAME}}:${{env.ENVIRONMENT}} .

      - name: Deploy in ec2 
        run: |
          /home/ubuntu/todo/prod/deploy.sh


