name: Build docker image
on: 
  push:
    branches:
      - main
env: 
  CONTEXT_PATH: .
  DOCKER_PATH: ./Dockerfile
  IMAGE_NAME: todo
  ENVIRONMENT: dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Build docker image
      #   run: |
      #     docker build -t ${{env.IMAGE_NAME}}:${{env.ENVIRONMENT}} .

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PUB_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          - name: Test SSH Connection
          run: |
            ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} whoami

      # - name: Add docker context
      #   uses: arwynfr/actions-docker-context@v2
      #   with:
      #     docker_host: 'ssh://${{ secrets.USERNAME}}@${{ secrets.HOST }}'
      #     context_name: 'ubuntu-server'
      #     ssh_cert: ${{ secrets.PUB_KEY }}
      #     ssh_key: ${{ secrets.KEY }}

      # - run: docker --context ubuntu-server run -d nginx:alpine



      # - name: Deploy in ec2 
      #   run: |
      #     /home/ubuntu/template/todo_dev/deploy.sh


