name: Build docker image
on: 
  push:
    branches:
      - main
env: 
  CONTEXT_PATH: .
  DOCKER_PATH: ./Dockerfile
  IMAGE_NAME: todo
  ENVIRONMENT: dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Build docker image
      #   run: |
      #     docker build -t ${{env.IMAGE_NAME}}:${{env.ENVIRONMENT}} .

      - name: SSh into server 
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo docker stop 8016e03f2236


      # - name: Deploy in ec2 
      #   run: |
      #     /home/ubuntu/template/todo_dev/deploy.sh


