name: Build frontend and push to S3 bucket

on:
  workflow_dispatch:

jobs:
  build:
    name: Build project , increase version, copy to S3
    runs-on: self-hosted
    steps:
      - name: Github Checkout
        uses: actions/checkout@v2
      - name: Node version setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies and Build
        run: |
          npm install
          npm run build

      - name: Copy files to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: ${{ secrets.VM_PORT }} # Change this to your VM's SSH port if different
          script: |
            sudo cp -r ./dist/* /var/www/html