name: Build frontend and push to S3 bucket

on:
  workflow_dispatch:

jobs:
  build:
    name: Build project , increase version, copy to S3
    runs-on: ubuntu-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v2
      - name: Node version setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies and Build
        run: |
          npm install
          npm run build

      - name: Push dist to aws S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION
          aws s3 cp ./dist/ s3://sulav-s3-bucket --recursive