name: Build docker image
on: 
  push:
    branches:
      - main
env: 
  CONTEXT_PATH: .
  DOCKER_PATH: ./Dockerfile
  IMAGE_NAME: todo
  ENVIRONMENT: dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Build docker image
      #   run: |
      #     docker build -t ${{env.IMAGE_NAME}}:${{env.ENVIRONMENT}} .

      - name: SSh into server 
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: whoami

      - name: Add docker context
        uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: 'ssh://${{ secrets.USERNAME}}@${{ secrets.HOST }}'
          context_name: 'ubuntu-server'
          ssh_cert: ${{ secrets.PUB_KEY }}
          ssh_key: ${{ secrets.KEY }}

      - run: docker --context ubuntu-server stop fd9e03484b33



      # - name: Deploy in ec2 
      #   run: |
      #     /home/ubuntu/template/todo_dev/deploy.sh


